version: '3.8'

services:
  sample-service:
    image: sample-service:latest
    container_name: sample-service
    depends_on:
      - log-router
      - datadog-agent
    ports:
      - 9000:8080
    environment:
      - DD_ENV=${ENV}
      - DD_SERVICE=sample-service
      - DD_LOGS_INJECTION=true
      - DD_PROFILING_ENABLED=true
      - DD_AGENT_HOST=datadog-agent


    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"


  greet-service:
    image: greet-service:latest
    container_name: greet-service
    depends_on:
      - log-router
      - datadog-agent
    environment:
      - DD_ENV=${ENV}
      - DD_SERVICE=greet-service
      - DD_LOGS_INJECTION=true
      - DD_PROFILING_ENABLED=true
      - DD_AGENT_HOST=datadog-agent

    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"


  log-router:
    image: fluent/fluent-bit:latest
    ports:
      - "24224:24224"
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - ENV=${ENV}
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  datadog-agent:
    image: datadog/agent:7.64.3
    container_name: datadog-agent
    ports:
      - 8126:8126
    environment:
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_ENV=${ENV}
      - DD_API_KEY=${DD_API_KEY}
      - DD_LOGS_ENABLED=false
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
