version: '3.8'

services:
  sample-service:
    image: sample-service:latest
    container_name: sample-service
    depends_on:
      - log-router
    ports:
      - 9000:8080
    environment:
      - ENV=dev
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"


  greet-service:
    image: greet-service:latest
    container_name: greet-service
    depends_on:
      - log-router
    environment:
      - ENV=dev
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"


  log-router:
    image: fluent/fluent-bit:latest
    ports:
      - "24224:24224"
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - ENV=dev
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  # datadog:
  #  image: gcr.io/datadoghq/agent:7
  #  container_name: datadog-agent
  #  environment:
  #    - DD_SITE=datadoghq.com
  #    - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
  #    - DD_ENV=dev
  #    - DD_API_KEY=${DD_API_KEY}
     
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #    - /proc/:/host/proc/:ro
  #    - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
  #    - /var/lib/docker/containers:/var/lib/docker/containers:ro





