version: '3.8'

services:
  sample-service:
    image: sample-service:latest
    container_name: sample-service
    depends_on:
      - log-router
    ports:
      - 9000:8080


    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"


  greet-service:
    image: greet-service:latest
    container_name: greet-service
    depends_on:
      - log-router
    
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"


  log-router:
    image: fluent/fluent-bit:latest
    ports:
      - "24224:24224"
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - ENV=${ENV}
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  